### ISSUE TITLE
Loading multiple pages at start 

### ISSUE THREAD

**Issue by FarshidABZ** [googlecodelabs/android-paging#106] opened 2020-09-11 15:02 UTC
When I close and run the application again, it loads the fourth pages. actually it calls GitHub's API for fourth pages. 
Why it does happening? 

![Screen Shot 2020-09-11 at 17 59 24](https://user-images.githubusercontent.com/5930617/92941294-dd943b00-f458-11ea-8d13-8702eb47c51e.png)

**Comment by rongcheng2017** [comment] 2020-10-09 10:30
I run the same problem!
![image](https://user-images.githubusercontent.com/28329834/95573091-81273a00-0a5d-11eb-9901-1e340c2a9654.png)

**Comment by johnjake** [comment] 2020-10-15 02:03
The problem was in Mediator make sure it uses the primary key of your DAO the annotated @PrimaryKey (`id`)
![image](https://user-images.githubusercontent.com/4056983/96067927-590c6080-0ecd-11eb-85b3-bc78fce5f990.png)

**Comment by Amineomed** [comment] 2020-10-16 02:24
the problem is the initialLoadSize in PagingConfig is set by default to pageSize * DEFAULT_INITIAL_PAGE_MULTIPLIER , you should make sure to add initialLoadSize = NETWORK_PAGE_SIZE u=in PagingConfig.

**Comment by florina-muntenescu** [comment] 2021-01-07 11:21
Fixed in #143

**Closed by florina-muntenescu** 2021-01-07 11:21 UTC
