### ISSUE TITLE
Duplicated items

### ISSUE THREAD

**Issue by CzarqR** [googlecodelabs/android-paging#135] opened 2020-12-08 17:02 UTC
When the app is using `PagingSource` (step12_separators) there are duplicated items in the `RecyclerView`. The first call load `150` items as the first page and the second call load `50` items as the second page. It seems to me like first call gives items from `1` to `150` and the second from `51` to `100`.   This is logcat:

```
https://api.github.com/search/repositories?sort=stars&q=Androidin%3Aname%2Cdescription&page=1&per_page=150
https://api.github.com/search/repositories?sort=stars&q=Androidin%3Aname%2Cdescription&page=2&per_page=50
```

Error can be removed by setting`initialLoadSize` the same as `pageSize` when creating `PagingConfig`
``` kotlin
config = PagingConfig(
    pageSize = NETWORK_PAGE_SIZE,
    enablePlaceholders = false,
    initialLoadSize = NETWORK_PAGE_SIZE
),
```

**Comment by shoanchikato** [comment] 2020-12-18 22:24
Duplicate of #79

**Comment by shehramjamil** [comment] 2020-12-31 23:09
Whenever the initialize and page sizes are same, app works fine and it becomes weird when both sizes are different and keep on calling the prepend and append loadstates in remote mediator.
TBH this library sucks

**Closed** 2021-01-07 11:13 UTC
